name = "BeamBeamInteraction"
uuid = "b220725c-5ae4-4e76-b121-3bd53397c127"
authors = ["Yue Hao <yuehao@msn.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
